kind: pipeline
name: Blaz1keN Drone

steps:
 - name: compile
   image: starlight2834/ci_docker:latest
   environment:
     BOT_API_KEY:
       from_secret: BOT_API_KEY
     CHAT_ID:
       from_secret: CHAT_ID
   commands:
      - apt-get -y update && apt-get -y upgrade && apt-get -y install git libxml2 && apt-get -y install gcc-arm-linux-gnueabi
      - cd /drone/src
      - bash kernel_setup.sh
